# the paths below assume youre are running the test
# from withing Baltica directory

path:
  /beegfs/homes/tbrittoborges/sirv_test/

# full path to the alignment files
sample_path:
  /beegfs/homes/tbrittoborges/Baltica/data/


samples:
  mix1_1: mix1_1.bam
  mix2_1: mix2_1.bam
  mix3_1: mix3_1.bam
  mix1_2: mix1_2.bam
  mix2_2: mix2_2.bam
  mix3_2: mix3_2.bam
  mix1_3: mix1_3.bam
  mix2_3: mix2_3.bam
  mix3_3: mix3_3.bam
  mix1_4: mix1_4.bam
  mix2_4: mix2_4.bam
  mix3_4: mix3_4.bam
  mix1_5: mix1_5.bam
  mix2_5: mix2_5.bam
  mix3_5: mix3_5.bam

# which comparison should we make?
# in the format case-vs-control
# conditions groups are extracted from '{group}_{replicate}'
contrasts:
  mix2-vs-mix1:
    - mix2
    - mix1
  mix3-vs-mix1:
    - mix3
    - mix1
  mix3-vs-mix2:
    - mix3
    - mix2

# This parameters is not currently used in Baltica
assembly:
  GRCh38_90_SIRV
# In case of doubt, please RSeQC infer_experiment result
strandness:
  reverse
# If the read length is variable, use the maximum
read_len:
  101
# full path to the reference transcriptome model
ref:
  /beegfs/homes/tbrittoborges/Baltica/data/SIRV.gtf
# full path to the reference sequence
ref_fa:
  /beegfs/homes/tbrittoborges/Baltica/data/SIRV.fa

# LeafCutter parameters to define cluster
min_samples_per_group:
  3
min_samples_per_intron:
  5

# Probability cut-off for Majiq
majiq_threshold:
  0.2
# adjusted p-value threshold for LeafCutter and JunctionSeq
fdr:
  0.05

#qc_env_prefix: source ~/miniconda3/etc/profile.d/conda.sh; conda init; conda activate qc;
#leafcutter_env_prefix: source ~/miniconda3/etc/profile.d/conda.sh; conda init; conda activate leafcutter;
#majiq_env_prefix: source ~/miniconda3/etc/profile.d/conda.sh; conda init; conda activate majiq;
#junctionseq_env_prefix: source ~/miniconda3/etc/profile.d/conda.sh; conda init; conda activate junctionseq;
#stringtie_env_prefix: source ~/miniconda3/etc/profile.d/conda.sh; conda init; conda activate stringtie;
#analysis_env_prefix: ""
