# example for three conditions in triplicate
samples:
  SampleA_1: SampleA_1.bam
  SampleA_2: SampleA_2.bam
  SampleA_3: SampleA_3.bam
  SampleB_1: SampleB_1.bam
  SampleB_2: SampleB_2.bam
  SampleB_3: SampleB_3.bam
  SampleC_1: SampleC_1.bam
  SampleC_2: SampleC_2.bam
  SampleC_3: SampleC_3.bam

# StringTie parameters
# minimun isoform fraction (default: .1)
min_iso:
  '-f 0.2'
# minimum anchor length for junctions (default: 10)
min_anchor_len:
 '-a 15'
# minimum junction coverage (default: 1)
min_junction_cov:
  '-j 5'
# reads are of the first (reverse) strand
rf:
  '--rf'

# Leafcutter parameters
min_samples_per_intron:
  '--min_samples_per_intron=2'
min_samples_per_group:
  '--min_samples_per_group=2'
fdr:
  '-f 0.05'

# Junctionseq parameters
max_read_length:
  '--maxReadLength 76'
min_count:
  '--minCount 3'
stranded:
  '--stranded'

# Majiq parameters
# path for the genome fasta for GC content composition correction
genome_path:
 '/GRCh38_90.fa'
threshold:
  '--threshold 0.1'
assembly:
  'Grch38'
#strandness=forward[|reverse|none]
strandness:
  'forward'
# general
#readlen : Length of the RNA-seq reads. MAJIQ the longest read length
read_len:
  76
gtf_path:
  GRCh38.90.gtf'