
sample_path:
  /path/to/samples

workdir:
  /path/to/workdir


samples:
  ctr_1: /path/1.bam
  ctr_2: /path/2.bam
  trt_1: /path/3.bam
  trt_2: /path/4.bam

ref:
  /path/GRCh38_90.gtf

ref_fa:
  /path/GRCh38_90.fa

strandness:
  reverse

# Majiq
threshold:
  --threshold 0.1
assembly:
  GRCh38_90
read_len:
  100

# LeafCutter
min_samples_per_group:
  3

min_samples_per_intron:
  5

fdr:
  0.05

contrasts:
  ctr-vs-trt:
    - ctr
    - trt


