samples:
  Luc_1: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49739_STARmapping/Aligned.noS.bam
  Luc_2: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49740_STARmapping/Aligned.noS.bam
  Luc_3: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49741_STARmapping/Aligned.noS.bam
  RNPS1_1: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49742_STARmapping/Aligned.noS.bam
  RNPS1_2: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49743_STARmapping/Aligned.noS.bam
  RNPS1_3: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49744_STARmapping/Aligned.noS.bam
  WTrescue_1: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49745_STARmapping/Aligned.noS.bam
  WTrescue_2: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49746_STARmapping/Aligned.noS.bam
  WTrescue_3: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49747_STARmapping/Aligned.noS.bam
  Mutrescue_1: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49748_STARmapping/Aligned.noS.bam
  Mutrescue_2: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49749_STARmapping/Aligned.noS.bam
  Mutrescue_2: /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_49750_STARmapping/Aligned.noS.bam

# StringTie

# -f minimun isoform fraction (default: .1)
min_iso:
  '-f 0.2'
# -a minimum anchor length for junctions (default: 10)
min_anchor_len:
 '-a 15'
# -j minimum junction coverage (default: 1)
min_junction_cov:
  '-j 5'
rf:
  '--rf'

# Leafcutter
min_samples_per_intron:
  '--min_samples_per_intron=2'
min_samples_per_group:
  '--min_samples_per_group=2'
fdr:
  '-f 0.05'

# Junctionseq
max_read_length:
  '--maxReadLength 76'
min_count:
  '--minCount 3'

# general
read_len:
  76
assembly:
  'Grch38'
genome_path:
 '/biodb/genomes/mus_musculus/GRCm38_79/GRCm38_79.fa'
