site_name: Baltica
site_url: https://github.com/dieterich-lab/Baltica
site_author: Thiago Britto-Borges
repo_url: https://github.com/dieterich-lab/Baltica
edit_uri: tree/master/docs/
site_description: Baltica - Integrated differential junction usage (DJU)
copyright: Thiago Britto-Borges, Dieterichlab - MIT License
use_directory_urls: false
docs_dir: docs/
theme:
  name: material
  language: 'en' 
  features:
    - instant
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: img/baltica_logo.ico
  favicon: img/baltica_logo.ico
extra_css:
    - extra.css

nav:
  - Index: index.md
  - Introduction: intro.md
  - Getting started: setup.md 
  - Project configuration: proj-config.md
  - Workflow implementation: workflows.md 
  - DJU methods result integration: integration.md 
  - Development guidelines: dev_guide.md
  - Frequently asked questions: faq.md
  - Tutorial: tutorial.md
  - References: bibliography.md
  - Release notes: release-notes.md 

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - attr_list

plugins:
  - search
  - bibtex:
      bib_file: "docs/bibliography.bib"
      cite_style: "pandoc"
  #- mkpdfs:
  #    author: "Thiago Britto Borges"
  #    design: "docs/report.css"
  #    output_path: "pdf/baltica_docs.pdf"
  #    toc_title: "Table of contents"
# https://squidfunk.github.io/mkdocs-material/reference/admonitions/#details


