# -f minimun isoform fraction (default: .1)
min_iso:
  '-f 0.2'
# -a minimum anchor length for junctions (default: 10)
min_anchor_len:
 '-a 15'
# -j minimum junction coverage (default: 1)
min_junction_cov:
  '-j 5'

samples:
 - /prj/Niels_Gehring/workflow_New_90/mapping/K002000065_*_STARmapping/Aligned.noS.bam
 

# names:
#  - Luc_1
#  - Luc_2
#  - Luc_3
#  - RNPS1_1
#  - RNPS1_2
#  - RNPS1_3
#  - WT_rescue_1
#  - WT_rescue_2
#  - WT_rescue_3
#  - Mut_rescue_1
#  - Mut_rescue_2
#  - Mut_rescue_3